Notices/Controllers/EmailController.cs
using Newtonsoft.Json;
using Notices.Core.Data;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Resources;
using System.Web;
using System.Web.Mvc;
using Notices.Extensions;
using Notices.Resources;
using System.Globalization;
using System.Collections;
using Notices.Models;
using Notices.Services;
using Clc.Polaris.Api;
using Notices.Security;
using Notices.Core;
using Clc.Polaris.Api.Models;
using System.Web.Script.Serialization;
using Notices.Core.Models;
using NLog;
using Notices.Services.Email;
using Hangfire;
using System.IO;
using Newtonsoft.Json.Linq;
using Clc.Auth;

namespace Notices.Controllers
{
    public class EmailController : Controller
    {
        DbHelper db;
        PapiClient papi;
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public EmailController()
        {
            db = new DbHelper(AppSettings.DbServer);
            papi = Methods.CreatePapiClient();
        }

        public ActionResult Index()
        {
            return Content("");
        }

        [ClcAuthorize(Roles ="Admin")]
        public string ViewExpirationReminderPatrons()
        {
            var notices = db.GetEmailNotices(new[] { NotificationType.ExpirationReminder }).Where(n => DbSettings.EmailEnableExpirationNotices(n.PatronBranch));

            return string.Join("\r\n", notices.Select(n => n.PatronID).Distinct());

        }

        public string SendNotices(NotificationType[] noticeTypes, string auth)
        {
            if (auth == AppSettings.AuthString)
            {
                if (!Methods.GetEmailSender().UseBackgroundJob || AppSettings.Dev)
                {
                    Email.SendNotices(noticeTypes);
                }
                else
                {
                    BackgroundJob.Enqueue(() => Email.SendNotices(noticeTypes, null));
                }

                return $"Sent {string.Join(", ", noticeTypes.Select(t => t.ToString()))}";
            }
            return "";
        }

        [ClcAuthorize(Roles ="Admin")]
        public ActionResult TestBounce(string email, string subject = "test subject", string sender = "sender@mail.com", string eventType = "HardBounce", string eventDescription = "")
        {
            if (!AppSettings.EnableEmailProcessing) return Content("email processing disabled in config");

            //var events = new List<MandrillMailEvent> { new MandrillMailEvent { Event = "hard_bounce", Msg = new Message { Subject = subject, Sender = sender, Email = email } } };
            //var fc = new FormCollection() { { "mandrill_events", new JavaScriptSerializer().Serialize(events) } };
            //ProcessFailure(fc, AppSettings.AuthString);

            var emailEvent = new EmailEvent
            {
                To = email,
                From = sender,
                Subject = subject,
                EventType = eventType,
                Description = eventDescription
            };

            var events = new List<EmailEvent> { emailEvent };
            ProcessFailedEmailEvents(events);

            return Content("test bounce processed");
        }

        [ClcAuthorize(Roles ="Admin")]
        public ActionResult TestSpam(string email, string subject = "test subject", string sender = "sender@mail.com")
        {
            if (!AppSettings.EnableEmailProcessing) return Content("email processing disabled in config");

            var emailEvent = new EmailEvent
            {
                To = email,
                From = sender,
                Subject = subject,
                EventType = "SpamComplaint",
                Description = ""
            };

            var events = new List<EmailEvent> { emailEvent };
            ProcessFailedEmailEvents(events);

            return Content("test spam processed");
        }

        [ClcAuthorize(Roles ="Admin")]
        public ActionResult TestUnsub(string barcode)
        {
            if (!AppSettings.EnableEmailProcessing) return Content("email processing disabled in config");

            ProcessUnsubscribe(barcode);
            return Content("test unsub processed");
        }

        [HttpGet]
        public ActionResult Unsubscribe()
        {
            return View(new UnsubscribeViewModel());
        }

        [HttpPost]
        public ActionResult Unsubscribe(UnsubscribeViewModel model)
        {
            if (!ModelState.IsValid) return View();
            var polaris = Methods.CreatePapiClient();

            if ((!polaris.PatronValidate(model.Barcode, model.Pin)?.Data?.ValidPatron) ?? false)
            {
                ModelState.AddModelError("", "Invalid barcode or pin");
                return View();
            }

            ProcessUnsubscribe(model.Barcode);

            return View("Unsubscribed");
        }

        [HttpGet]
        public ActionResult ViewTestNoticeEmail()
        {
            return View();
        }

        [ClcAuthorize]
        public ActionResult ViewExample()
        {
            var noticeTypes = new List<NotificationType> {
                            NotificationType.AlmostOverdueReminder,
                            NotificationType.FirstOverdue,
                            NotificationType.SecondOverdue,
                            NotificationType.ThirdOverdue,
                            NotificationType.Hold,
                            NotificationType.SecondHold,
                            NotificationType.ExpirationReminder,
                            NotificationType.Cancel
                        };

            var preds = new[]
            {
                Pred.Field<PolarisOrganization>(o=>o.OrganizationCodeID, "=", 3),
                Pred.Field<PolarisOrganization>(o=>o.Name, "not like", "z%")
            };

            var model = new ExampleEmailNoticeViewModel
            {
                AllOrganizations = db.PolarisOrganizations().ToList(),
                AvailableNotificationTypes =
                    new List<NotificationType> {
                            NotificationType.AlmostOverdueReminder,
                            NotificationType.FirstOverdue,
                            NotificationType.SecondOverdue,
                            NotificationType.ThirdOverdue,
                            NotificationType.Hold,
                            NotificationType.SecondHold,
                            NotificationType.ExpirationReminder,
                            NotificationType.Cancel
                    },
                NoticeTypeTest = new SelectList(noticeTypes.Select(nt => new SelectListItem { Text = nt.ToString(), Value = ((int)nt).ToString() }), "Value", "Text"),
                PolarisBranches = new SelectList(db.PolarisOrganizations(preds).OrderBy(o => o.Name).Select(o => new SelectListItem { Text = o.Name, Value = o.OrganizationID.ToString() }).ToList(), "Value", "Text")
            };


            return View(model);
        }



        [ClcAuthorize]
        public ActionResult Example(NotificationType? noticeType = null, int[] reportingOrgIds = null, int? patronBranchId = null, EmailFormat format = EmailFormat.Html)
        {
            reportingOrgIds = reportingOrgIds ?? new int[0];

            if (!noticeType.HasValue || !reportingOrgIds.Any() || !patronBranchId.HasValue) { return Content(""); }

            var notices = PolarisNotification.GenerateTest(new[] { noticeType.Value }, DeliveryOption.EmailAddress, patronBranchId.Value, reportingOrgIds);
            var email = Email.GenerateNoticeEmail(notices);
            return Content(format == EmailFormat.PlainText ? email.TextBody : email.HtmlBody, $"text/{format.ToString().ToLower()}");
        }

        [ClcAuthorize]
        public string RunNoticeTests(int patronBranch, int[] reportingBranchIds, NotificationType[] noticeTypes = null)
        {
            Email.RunTests(patronBranch, reportingBranchIds, noticeTypes, new OutputToFileEmailSender());
            return "done";
        }

        int GetLibrary(string emailDomain)
        {
            var orgId = db.GetLibraryFromEmailDomain(emailDomain);
            return orgId;
        }

        List<EmailEvent> GetMandrillEvents(FormCollection fc)
        {
            return fc.GetEvents()
                .Select(e => new EmailEvent
                {
                    To = e.Msg.Email,
                    From = e.Msg.Sender,
                    Subject = e.Msg.Subject,
                    EventType = e.Event,
                    Description = e.Msg.BounceDescription
                }).ToList();
        }

        List<EmailEvent> GetPostmarkEvents()
        {
            var bodyStream = new StreamReader(Request.InputStream);
            bodyStream.BaseStream.Seek(0, SeekOrigin.Begin);
            var bodyText = bodyStream.ReadToEnd();
            dynamic body = JObject.Parse(bodyText);

            var emailEvent = new EmailEvent
            {
                To = body.Email,
                From = body.From,
                Subject = body.Subject,
                EventType = body.Type,
                Description = body.Description
            };

            return new List<EmailEvent> { emailEvent };
        }

        [ValidateInput(false)]
        public ActionResult ProcessFailure(FormCollection fc, string auth)
        {
            if (!AppSettings.EnableEmailProcessing) return Content("email processing disabled in config");

            if (auth != AppSettings.AuthString) { return Content("invalid request"); }

            var events = new List<EmailEvent>();

            if (AppSettings.EmailProvider == "mandrill" || Request.UserAgent.ToLower().Contains("mandrill"))
            {
                if (!fc.AllKeys.Contains("mandrill_events"))
                {
                    logger.Trace("invalid request");
                    return Content("invalid request");
                }

                events = GetMandrillEvents(fc);
            }

Notices/Controllers/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using clc_twilio_csharp;

using Notices.Models;
using Notices.Services;
using clc_twilio_csharp.Models;
using Notices.Core.Data;
using Notices.Services.Postmark;
using Notices.Core;
using Notices.Core.Models;
using Clc.Auth;

namespace Notices.Controllers
{
    [ClcAuthorize(Roles = "Clc.Notices.ViewHistory")]
    public class HistoryController : Controller
    {
        TwilioClient twilio = Methods.CreateTwilioClient();
        PostmarkClient postmark = new PostmarkClient(AppSettings.PostmarkEmailKey);

        const int RECORDINGS_PER_PAGE = 1000;

        public ActionResult Calls(string pn)
        {
            if (string.IsNullOrWhiteSpace(pn))
            {
                //var test2 = twilio.ListCalls(new CallListRequest { To = pn });//.Calls.Where(c => c.Direction == "outbound-api").ToList();
                return View(new CallListModel { Calls = twilio.ListCalls().Data.Calls.Where(c => c.Direction == "outbound-api").ToList() });
            }

            return View(new CallListModel { Calls = twilio.ListCalls(to: pn).Data.Calls.Where(c => c.Direction == "outbound-api").ToList(), PhoneNumber = pn });
        }

        public ActionResult Listen(string callSid)
        {
            if (string.IsNullOrWhiteSpace(callSid))
                return Redirect("Index");

            var recording = twilio.ListRecordings(callSid: callSid).Data.Recordings.FirstOrDefault();

            if (recording != null)
            {
                return Redirect(string.Format("{0}{1}", "https://api.twilio.com", recording.Uri.ToString().Replace(".json", "")));
            }
            else
            {
                return View("InvalidRecording");
            }
        }

        public ActionResult Email(string email = "", bool extraDays = false)
        {
            var messages = new List<EmailHistoryItem>();

            if (!string.IsNullOrWhiteSpace(email))
            {
                new DbHelper(AppSettings.DbServer).AddEmailHistorySearchLog(User.Identity.GetPreferredUsername(), email);

                var postmark = new PostmarkClient(AppSettings.PostmarkEmailKey);
                var history = postmark.SearchMessages(email);
                var bounces = postmark.GetBounces(email)?.Bounces;
                postmark = new PostmarkClient(AppSettings.PostmarkDbKey);
                history.AddRange(postmark.SearchMessages(email));
                bounces.AddRange(postmark.GetBounces(email)?.Bounces);

                var bouncedMessageIds = bounces.Select(b => b.MessageId.ToString());

                messages = history.Select(h => h.ToEmailHistoryItem()).ToList();
                for (int i = 0; i < messages.Count; i++)
                {
                    if (bouncedMessageIds.Contains(messages[i].Id))
                    {
                        messages[i].Status = "bounced";
                    }
                }
            }

            var model = new EmailListViewModel(email, messages);

            return View(model);
        }

        public ActionResult EmailContent(string id)
        {
            var content = postmark.GetMessageContent(id);

            if (string.IsNullOrWhiteSpace(content?.TextBody) && string.IsNullOrWhiteSpace(content?.HtmlBody))
            {
                content = new PostmarkClient(AppSettings.PostmarkDbKey).GetMessageContent(id);
            }

            return Content(content.GetContent(), content.GetContentType());

            //return View((object)Mandrill.GetContent(id));
        }

        public List<Recording> GetOldRecordings()
        {
            var twilio = Methods.CreateTwilioClient();
            var recordings = new List<Recording>();

            var result = twilio.ListRecordings(startDateComparison: "<=", startDate: Dialout.RecordingCutOffDate);
            recordings.AddRange(result.Data.Recordings);
            while (result.Data.NextPageUri != null)
            {
                result = twilio.GetNextPage<RecordingList>(result.Data.NextPageUri);
                recordings.AddRange(result.Data.Recordings);
            }

            return recordings;
        }

        public ActionResult Sms(string pn)
        {
            List<SmsMessageViewModel> messages = LoadTelnyxMessages(pn);
            messages.AddRange(LoadTwilioMessages(pn));

            /*
            switch (AppSettings.SmsSender.ToLower())
            {
                case "telnyx":
                    messages = LoadTelnyxMessages(pn);
                    break;
                default:
                    messages = LoadTwilioMessages(pn);
                    break;
            }
            */

            return View(new MessageListViewModel(pn, messages));
        }

        List<SmsMessageViewModel> LoadTwilioMessages(string pn)
        {
            var messages = new List<SmsMessageViewModel>();
            if (string.IsNullOrWhiteSpace(pn))
            {
                messages = twilio.ListMessages(pageSize: 100).Data.Messages.Select(m => new SmsMessageViewModel(m)).ToList();
            }
            else
            {
                messages = twilio.GetSentMessages(pn, pageSize: 100).Data.Messages.Select(m => new SmsMessageViewModel(m)).ToList();
                messages.AddRange(twilio.ListMessages(to: pn, pageSize: 100).Data.Messages.Select(m => new SmsMessageViewModel(m)).ToList());
            }

            return messages;
        }

        List<SmsMessageViewModel> LoadTelnyxMessages(string pn)
        {
            var db = new DbHelper(AppSettings.DbServer);
            var messages = db.GetTelnyxSmsMessages(pn).ToList();

            return messages;
        }
    }
}

Notices/Views/History/Calls.cshtml
@model Notices.Models.CallListModel

<div id="container">
    @if (!string.IsNullOrWhiteSpace(Model.PhoneNumber))
    {
        <h2>Most Recent Calls Made to @Model.PhoneNumber</h2>
    }
    else
    {
        <h2>Recently Made Calls</h2>
    }
    @using (Html.BeginForm("Calls", "History", FormMethod.Get))
    {
        @Html.Label("Phone Number")@:&nbsp;
        @Html.TextBox("pn");
        <input type="submit" />
        if (!string.IsNullOrWhiteSpace(Model.PhoneNumber))
        {
            @Html.ActionLink("Clear", "Calls")
        }
    }
    <hr />
    <table id="calls" class="list-table">
        <tr>
            <th id="callsid_header" class="hidden">CallSid</th>
            <th>To</th>
            <th>Status</th>
            <th>Call Time</th>
            <th>Answered By</th>
            <th>Duration</th>
            <th>Listen</th>
        </tr>

        @foreach (var call in Model.Calls)
        {
            <tr>
                <td id="callsid_row" class="hidden">@call.Sid</td>
                <td>@call.To</td>
                <td>@call.Status</td>
                <td>
                    @if (call.StartTime.HasValue)
                    {
                        @call.StartTime.Value.ToLocalTime();
                    }
                </td>
                <td>@call.AnsweredBy</td>
                <td>@string.Format("{0} {1}", call.Duration, call.Duration > 1 ? "Seconds" : call.Duration > 0 ? "Second" : "")</td>
                <td>
                    @if (call.Duration > 0 && call.HasRecording())
                    {
                        @Html.ActionLink("Listen to call", "Listen", new { callSid = call.Sid }, new { target = "_blank" });
                    }
                </td>
            </tr>
        }

    </table>

    <script>
	if(window.location.href.indexOf("pn") < 0) {
       $(window).bind("pageshow", function() {
            $("#pn").val('');
        });
    }
    </script>
</div>

Notices/Views/History/Email.cshtml
@model EmailListViewModel
@{
    ViewBag.Title = "History";
}

<div id="container">

    @if (!string.IsNullOrWhiteSpace(Model.Address))
    {
        <h2>Emails Sent to @Model.Address in Last 45 Days</h2>
    }
    else
    {
        <h2>Enter an email address to search</h2>
    }
    @using (Html.BeginForm("Email", "History", FormMethod.Get))
    {
        @Html.Label("Email Address")@:&nbsp;
        @Html.TextBox("email");
        <input type="submit" />
        if (!string.IsNullOrWhiteSpace(Model.Address))
        {
            @Html.ActionLink("Clear", "email")
        }
    }
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>
                    Time
                </th>
                <th>
                    Subject
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>

        @foreach (var m in Model.Emails.OrderByDescending(msg => msg.ReceivedAt))
        {
            var isError = !m.Status.Equals("sent", StringComparison.OrdinalIgnoreCase);
            <tr class="@(isError ? "danger":"")">
                <td class="col-md-2">
                    @m.ReceivedAt.ToLocalTime().ToString("MM/dd/yyyy hh:mm tt")
                </td>
                <td class="col-md-9">
                    @Html.ActionLink(string.IsNullOrWhiteSpace(m.Subject) ? "None" : m.Subject, "EmailContent", new { id = m.Id }, new { target = "_blank" })
                </td>
                <td class="col-xs-1">
                    @m.Status
                </td>
            </tr>
        }
    </table>
</div>

<script>
    if (window.location.href.indexOf("email") < 0) {
        $(window).bind("pageshow", function () {
            $("#email").val('');
        });
    }
</script>

Notices/Views/History/EmailContent.cshtml
@model string
@{
    ViewBag.Title = "Email Content";
}

@Html.Raw(Model)

Notices/Views/History/Sms.cshtml
@model MessageListViewModel
@{
    ViewBag.Title = "History";
}

<div id="container">

    @if (!string.IsNullOrWhiteSpace(Model.PhoneNumber))
    {
        <h2>Most Recent Messages Sent to @Model.PhoneNumber</h2>
    }
    else
    {
        <h2>Recently Sent SMS</h2>
    }
    @using (Html.BeginForm("Sms", "History", FormMethod.Get))
    {
        @Html.Label("Phone Number")@:&nbsp;
        @Html.TextBox("pn");
        <input type="submit" />
        if (!string.IsNullOrWhiteSpace(Model.PhoneNumber))
        {
            @Html.ActionLink("Clear", "sms")
        }
    }
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>
                    Time
                </th>
                <th>
                    To
                </th>
                <th>
                    Message
                </th>
                <th>
                    Error
                </th>
            </tr>
        </thead>
        
        @foreach (var m in Model.Messages.OrderByDescending(msg => msg.DateSent))
        {
            <tr class="@(string.IsNullOrWhiteSpace(m.Error) ? "danger":"")">
                <td>
                    @(m.DateSent.ToLocalTime().ToString())
                </td>
                <td>
                    @m.To
                </td>
                <td>
                    @m.Body
                </td>
                <td>
                    @m.Error
                </td>
            </tr>
        }
    </table>
</div>

<script>
    if (window.location.href.indexOf("pn") < 0) {
        $(window).bind("pageshow", function () {
            $("#pn").val('');
        });
    }
</script>